plugins {
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management'
    id 'java'
    id("com.github.spotbugs") version "6.1.11"
}

configurations.all {
    exclude group: 'com.fasterxml.jackson.module', module: 'jackson-module-scala_2.13'
}

group = 'ru.katacademy.notification'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(Test).configureEach {
    testLogging {
        events = ["FAILED", "SKIPPED", "STANDARD_ERROR"]
        exceptionFormat = "FULL"
        showExceptions = true
        showCauses = true
        showStackTraces = true
        showStandardStreams = true
    }
}

tasks.spotbugsMain {
    reports {
        html {
            required = true
            outputLocation = file("$rootDir/build/reports/spotbugs/spotbugsMain.html")
            stylesheet = 'fancy-hist.xsl'
        }
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.spring.io/milestone' }
    maven { url = 'https://repo.spring.io/snapshot' }
}

dependencies {
    implementation platform(project(":bank-bom"))
    testImplementation platform(project(":bank-bom"))

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui"
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.liquibase:liquibase-core'

    implementation project(':bank-shared')

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

springBoot {
    mainClass = 'ru.katacademy.notification.NotificationServiceApplication'
}

tasks.named('test') {
    useJUnitPlatform()
}
