stages:
  - build

services:
  - name: confluentinc/cp-kafka:7.5.0
    alias: kafka
  - name: postgres:15
    alias: postgres
  - name: postgres:15
    alias: user-service_postgres

variables:
  POSTGRES_DB: userDB
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root

  USER_SERVICE_POSTGRES_DB: mainDB
  USER_SERVICE_POSTGRES_USER: root
  USER_SERVICE_POSTGRES_PASSWORD: root

before_script:
  - chmod +x gradlew
  - echo "Жду 30 секунд, пока поднимутся Postgres и Kafka..."
  - sleep 30

build:
  stage: build
  image: gradle:8.5-jdk21
  script:
    - ./gradlew clean build checkstyleMain checkstyleTest --no-daemon
  artifacts:
    when: always
    paths:
      - build/reports/checkstyle
      - build/reports/tests
