stages:
  - build

services:
  - wurstmeister/zookeeper:3.4.6
  - wurstmeister/kafka:2.13-2.8.1
  - postgres:15

variables:
  KAFKA_ZOOKEEPER_CONNECT: wurstmeister_zookeeper_1:2181
  KAFKA_ADVERTISED_HOST_NAME: wurstmeister_kafka_1
  POSTGRES_DB: userDB
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root

before_script:
  - chmod +x gradlew
  - echo "Жду 40 секунд, пока поднимутся Postgres, Zookeeper и Kafka..."
  - sleep 40

build:
  stage: build
  image: gradle:8.5-jdk21
  script:
    - ./gradlew clean build checkstyleMain checkstyleTest --no-daemon
  artifacts:
    when: always
    paths:
      - build/reports/checkstyle
      - build/reports/tests
