version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bankapp-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: userDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: