pluginManagement {
	repositories {
		maven { url = 'https://repo.spring.io/milestone' }
		maven { url = 'https://repo.spring.io/snapshot' }
		gradlePluginPortal()
	}
}

include("bank-shared")
include ("settings-service")
rootProject.name = 'bank-app'
include 'fraud-detection'
include 'audit'
include 'account-service'
