spring.application.name=myapp-backend
spring.profiles.active=dev

# PostgreSQL ? Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/myappdb
spring.datasource.username=myapp
spring.datasource.password=myapp
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=false

server.port=8050

# ?????????? data.sql ??? ??????
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Judge0 Configuration
judge0.url=http://localhost:2358
judge0.api-key=
judge0.timeout=30
