spring:
  application:
    name: api-gateway

logging:
  level:
    root: INFO

gateway:
  downstream:
    services:
      account-service:
        readiness-path: /actuator/health/readiness
      kyc-service:
        readiness-path: /actuator/health/readiness
      user-settings-service:
        readiness-path: /actuator/health/readiness
      audit-service:
        readiness-path: /actuator/health/readiness
      security-service:
        readiness-path: /actuator/health/readiness
      auth-statistics-service:
        readiness-path: /actuator/health/readiness
      fraud-detection:
        readiness-path: /actuator/health/readiness
      notification-service:
        readiness-path: /actuator/health/readiness