server:
  port: 8080

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: http://localhost:8083/v3/api-docs
      - name: settings-service
        url: http://localhost:8082/v3/api-docs
      - name: security-service
        url: http://localhost:8085/v3/api-docs