CREATE TABLE IF NOT EXISTS audit_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp VARCHAR(255),
    event_type VARCHAR(255),
    message VARCHAR(255),
    user_id VARCHAR(255)
);