plugins {
    id 'java-platform'
}

group = rootProject.group
version = rootProject.version

javaPlatform {
    allowDependencies()
}

dependencies {
    api platform("org.springframework.boot:spring-boot-dependencies:3.3.4")
    api platform("org.springframework.cloud:spring-cloud-dependencies:2023.0.5")
    api platform("com.fasterxml.jackson:jackson-bom:2.17.0")

    constraints {
        api "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0"

        api "org.projectlombok:lombok:1.18.30"
        api "org.liquibase:liquibase-core:4.27.0"
        api "org.postgresql:postgresql:42.7.3"
        api "io.micrometer:micrometer-registry-prometheus:1.13.4"

        api "org.mockito:mockito-core:5.5.0"
        api "org.mockito:mockito-junit-jupiter:5.5.0"
        api "com.h2database:h2:2.2.224"
        api 'io.minio:minio:8.5.7'

        api "org.testcontainers:junit-jupiter:1.19.8"
        api "org.testcontainers:kafka:1.19.8"
    }
}