server:
  port: 8080

spring:
  application:
    name: kyc-service

  # PostgreSQL Database Settings
  datasource:
    url: jdbc:postgresql://localhost:5435/kyc_verifications
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
