server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: security-service

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

bank:
  security:
    enabled: true