kyc:
  topics:
    events: kyc-events

server:
  port: 8080

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5433/mainDB
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
      bootstrap-servers: kafka:9092
      consumer:
        group-id: account-service
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        enable-auto-commit: false
        auto-offset-reset: latest
        properties:
          spring:
            json:
              trusted:
                packages: ru.katacademy.*
              use:
                type:
                  headers: false
              value:
                default:
                  type: ru.katacademy.bank_shared.event.kyc.KycStatusChangedEvent

## JPA / Hibernate
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#  spring.jpa.hibernate.ddl-auto=create-drop
#  spring.jpa.show-sql=true
#  spring.jpa.properties.hibernate.format_sql=true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: db, kafka
        liveness:
          include: ping

kyc-service:
  url: ${KYC_SERVICE_URL:http://kyc-service:8080}