server:
  port: 8080

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mainDB
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

## JPA / Hibernate
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#  spring.jpa.hibernate.ddl-auto=create-drop
#  spring.jpa.show-sql=true
#  spring.jpa.properties.hibernate.format_sql=true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
