server:
  port: 8080

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  datasource:
    url: jdbc:postgresql://postgres:5432/account_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092
    topic:
      transferCompleted: transfer-completed-events

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

flyway:
  enabled: false

kyc-service:
  url: http://kyc-service:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: db,kafka
        liveness:
          include: ping

bank:
  security:
    enabled: false