plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'checkstyle'
    id("com.github.spotbugs") version "6.1.11"
}

group = 'ru.katacademy'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

checkstyle {
    toolVersion = '10.12.3'
    configFile = rootProject.file("config/checkstyle/checkstyle.xml")
}

tasks.spotbugsMain {
    reports.create("html") {
        required = true
        outputLocation = file("$rootDir/build/reports/spotbugs/spotbugs.html")
        setStylesheet("fancy-hist.xsl")
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.spring.io/milestone' }
    maven { url = 'https://repo.spring.io/snapshot' }
}

dependencies {
    implementation platform(project(":bank-bom"))
    testImplementation platform(project(":bank-bom"))

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation project(":bank-shared")

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

bootJar {
    enabled = true
    archiveFileName = "security-service-${version}.jar"
}

jar {
    enabled = true
    archiveClassifier = 'plain'
}
