plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'checkstyle'
    id 'jacoco'
}

group = 'ru.katacademy.bank_app'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}
checkstyle {
    toolVersion = '10.12.3'
    configFile = file("$rootDir/config/checkstyle/checkstyle.xml")
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.spring.io/milestone' }
    maven { url = 'https://repo.spring.io/snapshot' }
}

dependencies {
    // Spring Boot Starters
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'javax.validation:validation-api:2.0.1.Final'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.glassfish:javax.el:3.0.0'
    implementation 'org.postgresql:postgresql:42.7.2'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.security:spring-security-crypto'
    implementation(project(":bank-shared"))

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Database
    runtimeOnly 'org.postgresql:postgresql'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'com.h2database:h2'
}

tasks.named('test') {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacoco {
    toolVersion = "0.8.11"
    reportsDirectory = layout.buildDirectory.dir("reports/jacoco") // Директория для отчетов
}

    // Конфигурация отчета JaCoCo
jacocoTestReport {
    dependsOn test // Отчет зависит от выполнения тестов
    reports {
        html.required = true // Локальный HTML-отчет
        csv.required = false // Если не нужен CSV
    }

    // включаем в  отчет определенные слои (domain,application)
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, includes: [
                    'ru/katacademy/bank_app/accountservice/domain/**',
                    'ru/katacademy/bank_app/accountservice/application/**'
            ])
        }))
    }
}

    // Проверка минимального покрытия
jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.8 // Минимум 80% покрытия
            }
        }
    }
}

    // Чтобы проверка coverage запускалась при выполнении check
check.dependsOn jacocoTestCoverageVerification
