plugins {
    id 'java-library'
    id("com.github.spotbugs") version "6.1.11"
}

group = 'ru.katacademy.bank-app'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api platform(project(":bank-bom"))

    annotationProcessor platform(project(":bank-bom"))
    compileOnly platform(project(":bank-bom"))
    testAnnotationProcessor platform(project(":bank-bom"))

    api 'com.fasterxml.jackson.core:jackson-databind'
    api 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    api 'jakarta.validation:jakarta.validation-api'
    api 'org.slf4j:slf4j-api'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    compileOnly 'com.github.spotbugs:spotbugs-annotations'
    compileOnly 'org.aspectj:aspectjrt'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}

tasks.spotbugsMain {
    reports.create("html") {
        required = true
        outputLocation = file("$rootDir/reports/spotbugs-bank-shared.html")
        stylesheet = 'fancy-hist.xsl'
    }
    excludeFilter = file("config/spotbugs/exclude-filter.xml")
}

check {
    dependsOn tasks.spotbugsMain, tasks.spotbugsTest
}

jar {
    enabled = true
    archiveClassifier = ''
}